name: 'Commit and Creating PR'
description: 'this action runs build command and push it in another repo with creating PR'
inputs:
  target-repo:
    required: true
    default: 'apetrosyan1613/test-repo1'
  source-repo-path:
    required: true
    default: 'specs'
  target-repo-path:
    required: true
    default: 'qase-javascript'
  build-command:
    required: true
    default: './Taskfile typescript'
  token:
    requre: true

outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
    - name: set branch name
      id: new_branch
      run: echo ::set-output name=new_branch::$(echo "client_update_$(date +'%Y-%m-%dT%H.%M.%S')")
      shell: bash
    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: ${{ inputs.source-repo-path }}
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        repository:  ${{ inputs.target-repo }}
        path: ${{ inputs.target-repo-path }}
        token: ${{ inputs.token }}
    - name: run js client generation
      working-directory: ./specs
      run: ${{ inputs.build-command }}
      shell: bash
    # - run: cp -R ./specs/examples/sdk/ts/* ./qase-javascript/qaseio/src
    # - id: git-check
    #   working-directory: ./qase-javascript
    #   run: echo ::set-output name=modified::$(if [ -n "$(git status --porcelain)" ]; then echo "true"; else echo "false"; fi)
    # - if: steps.git-check.outputs.modified == 'true'
    #   working-directory: ./qase-javascript
    #   run: |
    #    git config --global user.name 'Sergey Skaridov'
    #    git config --global user.email 's.skaridov@gmail.com'
    #    git checkout -b ${{ steps.new_branch.outputs.new_branch }}
    #    git add -A
    #    git commit -m '[build] update client'
    #    git push --set-upstream origin ${{ steps.new_branch.outputs.new_branch }}
    # - name: create pr
    #   id: create_pr
    #   uses: octokit/request-action@v2.x
    #   with:
    #     route: POST /repos/{owner}/{repo}/pulls
    #     owner: sklmx
    #     repo: qase-javascript
    #     base: 'master'
    #     head: ${{ steps.new_branch.outputs.new_branch }}
    #     title: 'Specs updated'
    #     body: 'This PR is auto-generated'
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.JS_REPO_TOKEN }}


