name: 'Commit and Creating PR'
description: 'this action runs build command and push it in another repo with creating PR'
inputs:
  target-repo:
    required: true
    default: 'apetrosyan1613/test-repo1'
  source-repo-path:
    required: true
    default: 'specs'
  target-repo-path:
    required: true
    default: 'qase-javascript'
  build-command:
    required: true
    default: './Taskfile typescript'
  token:
    requre: true
  source-copy-dir:
    required: true
    default: ''   
  target-copy-dir:
    required: true
    default: ''
  git-username:
    required: true
    default: '' 
  git-email:
    required: true
    default: '' 
  commit-message:
    required: true
    default: ''     

outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
    - name: set branch name
      id: new_branch
      run: echo ::set-output name=new_branch::$(echo "client_update_$(date +'%Y-%m-%dT%H.%M.%S')")
      shell: bash
    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: ${{ inputs.source-repo-path }}
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        repository:  ${{ inputs.target-repo }}
        path: ${{ inputs.target-repo-path }}
        token: ${{ inputs.token }}
    - name: run js client generation
      working-directory: ${{ inputs.source-repo-path }}
      run: ${{ inputs.build-command }}
      shell: bash
    - run: ls && ls {{ inputs.source-copy-dir }} && ls ${{ inputs.target-copy-dir }} && cp -R ${{ inputs.source-copy-dir }} ${{ inputs.target-copy-dir }}
      shell: bash
    - id: git-check
      working-directory: ${{ inputs.target-repo-path }}
      run: echo ::set-output name=modified::$(if [ -n "$(git status --porcelain)" ]; then echo "true"; else echo "false"; fi)
      shell: bash
    - if: steps.git-check.outputs.modified == 'true'
      shell: bash
      working-directory: ${{ inputs.target-repo-path }}
      run: |
       git config --global user.name "${{ inputs.git-username }}"
       git config --global user.email "${{ inputs.git-email }}"
       git checkout -b ${{ steps.new_branch.outputs.new_branch }}
       git add -A
       git commit -m ${{ inputs.commit-message }}
       git push --set-upstream origin ${{ steps.new_branch.outputs.new_branch }}
    # - name: create pr
    #   id: create_pr
    #   uses: octokit/request-action@v2.x
    #   with:
    #     route: POST /repos/{owner}/{repo}/pulls
    #     owner: sklmx
    #     repo: qase-javascript
    #     base: 'master'
    #     head: ${{ steps.new_branch.outputs.new_branch }}
    #     title: 'Specs updated'
    #     body: 'This PR is auto-generated'
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.JS_REPO_TOKEN }}


